

#!/bin/sh

# Oracle Database connection information
USER="akward"
PASSWORD="05032458"
CONNECTION_STRING="(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(Host=oracle.scs.ryerson.ca)(Port=1521))(CONNECT_DATA=(SID=orcl)))"

# Use SQL*Plus to run the SQL statements
#Code to drop all tables 
sqlplus64 "$USER/$PASSWORD@$CONNECTION_STRING" <<EOF

DROP TABLE ADMINLOGINS CASCADE CONSTRAINTS;
DROP TABLE BOOKINGS CASCADE CONSTRAINTS;
DROP TABLE FORMATIONS CASCADE CONSTRAINTS;
DROP TABLE GOALS CASCADE CONSTRAINTS;
DROP TABLE MANAGEMENTSTAFF CASCADE CONSTRAINTS;
DROP TABLE MATCHEST CASCADE CONSTRAINTS;
DROP TABLE PLAYERS CASCADE CONSTRAINTS;
DROP TABLE REFEREES CASCADE CONSTRAINTS;
DROP TABLE TEAMS CASCADE CONSTRAINTS;
DROP TABLE USERLOGINS CASCADE CONSTRAINTS;

EOF

