
#!/bin/sh

# Oracle Database connection information
USER="akward"
PASSWORD="05032458"
CONNECTION_STRING="(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(Host=oracle.scs.ryerson.ca)(Port=1521))(CONNECT_DATA=(SID=orcl)))"

# Use SQL*Plus to run the SQL statements
sqlplus64 "$USER/$PASSWORD@$CONNECTION_STRING" <<EOF

CREATE VIEW LeaderboardVIEW (TeamName, Wins, Losses, Tie, Points, Matches_Played) AS
(SELECT  TeamName, WINSTHISSEASON, LOSSESTHISSEASON, TIESTHISSEASON, (WINSTHISSEASON * 3 + TIESTHISSEASON * 1), (WINSTHISSEASON + LOSSESTHISSEASON + TIESTHISSEASON)
FROM TEAMS);

exit;
EOF
